# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Communication.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'Communication.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x43ommunication.proto\"\x1a\n\x07Request\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1b\n\x08Response\x12\x0f\n\x07message\x18\x01 \x01(\t\"-\n\x11UpdateInfoRequest\x12\n\n\x02ip\x18\x01 \x01(\t\x12\x0c\n\x04role\x18\x02 \x01(\t\"&\n\x12UpdateInfoResponse\x12\x10\n\x08response\x18\x01 \x01(\t\"\x1c\n\x0cWriteRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\" \n\rWriteResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1a\n\x0bReadRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\"\x1c\n\x0cReadResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t2\xce\x01\n\x14\x63ommunicationHandler\x12#\n\x0c\x43lient_Proxy\x12\x08.Request\x1a\t.Response\x12\x36\n\x0bUpdateNodes\x12\x12.UpdateInfoRequest\x1a\x13.UpdateInfoResponse\x12-\n\x0cWriteProcess\x12\r.WriteRequest\x1a\x0e.WriteResponse\x12*\n\x0bReadProcess\x12\x0c.ReadRequest\x1a\r.ReadResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Communication_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REQUEST']._serialized_start=23
  _globals['_REQUEST']._serialized_end=49
  _globals['_RESPONSE']._serialized_start=51
  _globals['_RESPONSE']._serialized_end=78
  _globals['_UPDATEINFOREQUEST']._serialized_start=80
  _globals['_UPDATEINFOREQUEST']._serialized_end=125
  _globals['_UPDATEINFORESPONSE']._serialized_start=127
  _globals['_UPDATEINFORESPONSE']._serialized_end=165
  _globals['_WRITEREQUEST']._serialized_start=167
  _globals['_WRITEREQUEST']._serialized_end=195
  _globals['_WRITERESPONSE']._serialized_start=197
  _globals['_WRITERESPONSE']._serialized_end=229
  _globals['_READREQUEST']._serialized_start=231
  _globals['_READREQUEST']._serialized_end=257
  _globals['_READRESPONSE']._serialized_start=259
  _globals['_READRESPONSE']._serialized_end=287
  _globals['_COMMUNICATIONHANDLER']._serialized_start=290
  _globals['_COMMUNICATIONHANDLER']._serialized_end=496
# @@protoc_insertion_point(module_scope)
