# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Communication.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'Communication.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x43ommunication.proto\"\x1a\n\x08GRequest\x12\x0e\n\x06number\x18\x01 \x01(\x05\"\x1b\n\tGResponse\x12\x0e\n\x06number\x18\x01 \x01(\x05\"\x1a\n\x07Request\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1b\n\x08Response\x12\x0f\n\x07message\x18\x01 \x01(\t\"-\n\x11UpdateInfoRequest\x12\n\n\x02ip\x18\x01 \x01(\t\x12\x0c\n\x04role\x18\x02 \x01(\t\"~\n\x12UpdateInfoResponse\x12\x36\n\nnodes_info\x18\x01 \x03(\x0b\x32\".UpdateInfoResponse.NodesInfoEntry\x1a\x30\n\x0eNodesInfoEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x1c\n\x0cWriteRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\" \n\rWriteResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1a\n\x0bReadRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\"\x1c\n\x0cReadResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\"\'\n\x14\x44isconnectionRequest\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\"(\n\x15\x44isconnectionResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1f\n\x0c\x41rrayRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x16\n\x05\x41rray\x12\r\n\x05\x61rray\x18\x01 \x03(\t\"2\n\x19LeaderNotificationRequest\x12\x15\n\rnew_leader_ip\x18\x01 \x01(\t2\x82\x04\n\x14\x63ommunicationHandler\x12#\n\x0c\x43lient_Proxy\x12\x08.Request\x1a\t.Response\x12\x36\n\x0bUpdateNodes\x12\x12.UpdateInfoRequest\x1a\x13.UpdateInfoResponse\x12>\n\rDisconnection\x12\x15.DisconnectionRequest\x1a\x16.DisconnectionResponse\x12\x36\n\x13\x44isconnectionUpdate\x12\x13.UpdateInfoResponse\x1a\n.GResponse\x12-\n\x0cWriteProcess\x12\r.WriteRequest\x1a\x0e.WriteResponse\x12*\n\x0bReadProcess\x12\x0c.ReadRequest\x1a\r.ReadResponse\x12*\n\rAppendEntries\x12\r.WriteRequest\x1a\n.GResponse\x12)\n\x10UpdateWriteArray\x12\r.ArrayRequest\x1a\x06.Array\x12\"\n\tHeartbeat\x12\t.GRequest\x1a\n.GResponse\x12?\n\x15NewLeaderNotification\x12\x1a.LeaderNotificationRequest\x1a\n.GResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Communication_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_UPDATEINFORESPONSE_NODESINFOENTRY']._loaded_options = None
  _globals['_UPDATEINFORESPONSE_NODESINFOENTRY']._serialized_options = b'8\001'
  _globals['_GREQUEST']._serialized_start=23
  _globals['_GREQUEST']._serialized_end=49
  _globals['_GRESPONSE']._serialized_start=51
  _globals['_GRESPONSE']._serialized_end=78
  _globals['_REQUEST']._serialized_start=80
  _globals['_REQUEST']._serialized_end=106
  _globals['_RESPONSE']._serialized_start=108
  _globals['_RESPONSE']._serialized_end=135
  _globals['_UPDATEINFOREQUEST']._serialized_start=137
  _globals['_UPDATEINFOREQUEST']._serialized_end=182
  _globals['_UPDATEINFORESPONSE']._serialized_start=184
  _globals['_UPDATEINFORESPONSE']._serialized_end=310
  _globals['_UPDATEINFORESPONSE_NODESINFOENTRY']._serialized_start=262
  _globals['_UPDATEINFORESPONSE_NODESINFOENTRY']._serialized_end=310
  _globals['_WRITEREQUEST']._serialized_start=312
  _globals['_WRITEREQUEST']._serialized_end=340
  _globals['_WRITERESPONSE']._serialized_start=342
  _globals['_WRITERESPONSE']._serialized_end=374
  _globals['_READREQUEST']._serialized_start=376
  _globals['_READREQUEST']._serialized_end=402
  _globals['_READRESPONSE']._serialized_start=404
  _globals['_READRESPONSE']._serialized_end=432
  _globals['_DISCONNECTIONREQUEST']._serialized_start=434
  _globals['_DISCONNECTIONREQUEST']._serialized_end=473
  _globals['_DISCONNECTIONRESPONSE']._serialized_start=475
  _globals['_DISCONNECTIONRESPONSE']._serialized_end=515
  _globals['_ARRAYREQUEST']._serialized_start=517
  _globals['_ARRAYREQUEST']._serialized_end=548
  _globals['_ARRAY']._serialized_start=550
  _globals['_ARRAY']._serialized_end=572
  _globals['_LEADERNOTIFICATIONREQUEST']._serialized_start=574
  _globals['_LEADERNOTIFICATIONREQUEST']._serialized_end=624
  _globals['_COMMUNICATIONHANDLER']._serialized_start=627
  _globals['_COMMUNICATIONHANDLER']._serialized_end=1141
# @@protoc_insertion_point(module_scope)
